language: python
python:
  - "2.6"
  - "2.7"

install:
  - mkdir void
  - mkdir void/Github
  - cp -R * void/Github/ || true
  - git clone https://github.com/ProgVal/Limnoria.git limnoria
  - pip install coverage
  - cd limnoria
  - python setup.py install
  - cd ../void/Github

script:
  - python ../../limnoria/scripts/supybot-test --plugins-dir=.. Github

after_success:
  - coverage run --branch --source plugin.py,local --omit '*init*' ../../limnoria/scripts/supybot-test --plugins-dir=.. Github
  - coverage report -m

notifications:
  webhooks:
    - http://helit.tech:8093/++alezakos

sudo: false
